[package]
name = "moonwalk-back"
version = "1.0.0"
edition = "2018"

[dependencies]
colored = "2.0.0"
users = "0.11.0"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
once_cell = "1.9.0"

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1
